#  Ⅳ-1-2 퍼셉트론
### 퍼셉트론으로 AND, OR, NOT, XOR 연산 구현하기

입력값에 가중치를 곱해서 활성화 함수에 넣고, 그 값을 출력값으로 한다.

- 오차역전파
  - 출력층으로부터 거슬러 올라가며 가중치를 업데이트하는 방법으로 경사하강법의 경우 미분값을 이용해 가중치를 업데이트한다.
  - 퍼셉트론에서 사용하는 sigmoid 함수의 경우 미분값의 최대치가 1보다 작은 특성이 있어 계속 곱할 경우 0에 수렴함.
- 활성화 함수
  - 신호를 받았을 때 출력을 보낼지 말지 결정하는 함수로, Sigmoid 개형의 함수를 사용한다.
  - 다중 분류의 경우 Softmax 함수를 사용한다.
  - 회귀분석의 경우 항등함수를 사용함.
  - 일반적으로 ReLU, tanh 함수를 사용한다.
- 손실 함수
  - 오차가 얼마나 되는지를 측정하는 함수
  - 손실 함수로 측정된 손실을 최소화하는 방법을 찾아야 함
- 최적화 기법
  - 가중치를 업데이트하는 방법으로 경사하강법이 있다.
  - 계산량이 많다는 단점이 있음 (모든 구간을 미분해야 함)


### 논리 게이트
- AND 게이트
- OR 게이트
- NOR 게이트
- XOR 게이트
  - 두 입력값이 다를 때 True를 출력한다.
  - 평면상에서 직선 하나로 분류하지 못한다.
- NOT 게이트
- XNOR 게이트
- NAND 게이트

1. 라이브러리를 불러온다.

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse

## AND 연산

2. 데이터를 입력하여 AND 연산을 구현해 보고 결과를 확인한다.

In [ ]:
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기                      A   B
data = np.array([[0, 0],          ##   0   0
                 [0, 1],          ##   0   1
                 [1, 0],          ##   1   0
                 [1, 1]])         ##   1   1
                                  ##   S
output = np.array([[0],           ##   0
                  [0],            ##   0
                  [0],            ##   0
                  [1]])           ##   1

3. 단층 퍼셉트론 모델을 구성한다.

In [ ]:
model = Sequential()
model.add(Dense(1, input_shape = (2, ), activation = 'linear'))
#단층 퍼셉트론이므로 한 개의 층만 추가한다.
# Activaton: 활성화 함수를 지정한다. 이 경우 선형으로 지정함

In [ ]:
# 모델 준비하기
model.compile(optimizer = SGD(), loss = mse, metrics = ['acc'])

- Optimizer: 최적화
  - 최적화 기법을 설정해 주는 요소이다.
  - 확률적 경사하강법 (SGD)
  - 모멘텀 (Momentum)
  - 아다그라드(Adagrad)
  - 아엠에스프롭 (RMSProp)
  - 아담 (Adam)
- loss: 손실 함수
  - 평균제곱오차 (mean_squared_error, mse)
  - 평균절대오차
  - 이항 교차 엔트로피
  -

4. 학습을 실행한다.

In [ ]:
# 에폭은 약 500번 정도
model.fit(data, output, epochs = 500)

5. 가중치와 바이어스 확인하고 결과를 적는다.

In [ ]:
# 가중치와 바이어스를 확인합니다.
model.get_weights()

6. 데이터를 직접 입력하여 활성화 함수의 기준점을 짐작해 보고 결과를 해석한다.

In [ ]:
k = model.predict(np.array([[int(input("입력 : ")) for j in range(2)] for i in range(1)]))
k

왜 애매하게 이상한 숫자가 나왔을까?
- 계산하는 것이 아니라 확률적으로 추측하는 것이기 때문이다.

7. OR, NOT, XOR 데이터를 입력한 다음 기준점을 생각해 보고 결과를 해석하여 적
는다.

## OR 연산

In [ ]:
# OR 연산
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기
data = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])
output=np.array([[0],[1],[1],[1]])

In [15]:
# 모델 구성하기    # 단층 퍼셉트론을 구성합니다
model = Sequential()
model.add(Dense(1,input_shape=(2, ), activation='linear'))

In [16]:
# 모델 준비하기
model.compile(optimizer = 'adam', loss = mse, metrics = ['acc'])

In [17]:
# 학습시키기
model.fit(data, output, epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 719ms/step - acc: 0.7500 - loss: 0.9743
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - acc: 0.7500 - loss: 0.9722
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.9700
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.9678
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.9657
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - acc: 0.7500 - loss: 0.9635
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.9614
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.7500 - loss: 0.9592
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.7500 - loss: 0.9571
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.9550
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - acc: 0.7500 - loss: 0.9529
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - acc: 0.7500 - loss: 0.9508
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/st

In [21]:
# 가중치와 바이어스를 확인합니다.
model.get_weights()

[array([[ 0.4464858 ],
        [-0.55464095]], dtype=float32),
 array([0.38551727], dtype=float32)]

In [23]:
# 데이터 넣어서 확인하기
k = model.predict(np.array([[int(input("입력 : ")) for j in range(2)] for i in range(1)]))
k

입력 : 0
입력 : 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[-0.16912368]], dtype=float32)

# NOT연산

In [ ]:
# NOT 연산
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기
data = np.array([[0],
                 [1]])

output = np.array([[1],[0]])

In [ ]:
# 모델 구성하기      # 단층 퍼셉트론을 구성합니다
model = Sequential()
model.add(Dense(1, input_shape=(1,), activation="linear"))

In [ ]:
# 모델 준비하기
model.compile(optimizer = SGD(), lose=mse, metrics=['acc'])

In [ ]:
# 학습시키기
model.fit(data, output, epochs = 500)


In [ ]:
# 가중치와 바이어스를 확인합니다.
model.get_weights()

In [ ]:
# 데이터 넣어서 확인하기
k = model.predict(np.array([[int(input("입력 : ")) for j in range(1)] for i in range(1)]))
k

# 4. XOR연산

In [3]:
# XOR 연산
tf.random.set_seed(807) # 시드를 배정합니다.

# 데이터 준비하기
data = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])
output = np.array([[0],[1],[1],[0]])

In [4]:
model = Sequential()
model.add(Dense(30, input_shape = (2, ), activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1,  activation = 'sigmoid'))
#단층 퍼셉트론이므로 한 개의 층만 추가한다.
# Activaton: 활성화 함수를 지정한다. 이 경우 선형으로 지정함

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
# 모델 준비하기
model.compile(optimizer = 'adam', loss = mse, metrics = ['acc'])

In [6]:
# 에폭은 약 500번 정도
model.fit(data, output, epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - acc: 0.7500 - loss: 0.2446
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.2437
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - acc: 0.5000 - loss: 0.2431
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 0.7500 - loss: 0.2423
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - acc: 0.7500 - loss: 0.2414
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.7500 - loss: 0.2405
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7500 - loss: 0.2396
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7500 - loss: 0.2388
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7500 - loss: 0.2383
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 0.7500 - loss: 0.2377
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7500 - loss: 0.2371
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 0.7500 - loss: 0.2365
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step 

In [7]:
# 가중치와 바이어스를 확인합니다.
model.get_weights()

[array([[-0.28122702,  0.18645169,  0.28987387,  0.47840586, -0.39777714,
          0.29744533, -0.10136612, -0.2627396 , -0.02830607, -0.40974712,
         -0.2956315 ,  0.43272114,  0.57489043,  0.48317066,  0.0328033 ,
         -0.36517057, -0.08068773,  0.4345145 ,  0.30138436,  0.25359154,
         -0.4955936 , -0.19964547, -0.29589617,  0.4712867 ,  0.2573931 ,
         -0.3561034 ,  0.52385557, -0.03538719, -0.2927159 ,  0.3961593 ],
        [ 0.5089251 ,  0.5327233 , -0.40155002,  0.03922078,  0.28844938,
          0.44520777,  0.5453766 ,  0.4719369 , -0.15932846, -0.271605  ,
          0.29564947,  0.19062413, -0.07235646, -0.08789331, -0.13165244,
          0.3651703 , -0.35631955, -0.47658774, -0.30134818,  0.36199883,
          0.29813287, -0.04340601,  0.31203082, -0.47130868,  0.11115605,
          0.35611472, -0.42736915, -0.0810656 , -0.1520674 , -0.18176332]],
       dtype=float32),
 array([ 9.2059538e-02,  9.8998278e-02,  2.8924933e-01, -3.8162094e-02,
         2.213

In [11]:
# 데이터 넣어서 확인하기
k = model.predict(np.array([[int(input("입력 : ")) for j in range(2)] for i in range(1)]))
k
# 단일 퍼셉트론으론 XOR 연산을 구분할 수 없다.

입력 : 1
입력 : 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[0.01939922]], dtype=float32)